# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_recolysis_wrappers", use_symbols = TRUE, package_name = "recolysis")

#' @usage NULL
#' @useDynLib recolysis, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' IDK what this does
#' @export
determ_pva <- function(survival_matrix, population_matrix, generations) invisible(.Call(wrap__determ_pva, survival_matrix, population_matrix, generations))


# nolint end
